site_name: cornucopia
site_url: https://cornucopia.readthedocs.io
repo_url: https://github.com/balbasty/cornucopia
edit_uri: blob/main/docs
site_dir: html
docs_dir: docs
theme:
  name: material
  palette:
    primary: orange
    accent: orange
  icon:
    repo: fontawesome/brands/github
  logo:
    icons/cc_full_white.svg
extra_css:
  - stylesheets/extra.css
plugins:
- mkdocs-jupyter
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          docstring_style: numpy
          merge_init_into_class: True
          separate_signature: True
          members_order: source
          show_source: False
          show_root_heading: True
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.arithmatex:
    generic: true
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Home: index.md
- Installation: install.md
- Getting Started: start.md
- Examples:
  -  Overview: examples/overview.md
  -  Field-of-view transforms: examples/fov.ipynb
  -  Noise transforms: examples/noise.ipynb
  -  Geometric transforms: examples/geom.ipynb
  -  Random intra-scan motion: examples/motion.ipynb
  -  Contrast augmentation: examples/contrast.ipynb
  -  Label augmentation: examples/labels.ipynb
  -  Synthetic MRIs: examples/synth.ipynb
  -  Quantitative MRIs: examples/qmri.ipynb
  -  Random coil sensitivities: examples/coils.ipynb
  -  Benchmark: examples/benchmark.ipynb
- API:
  - overview: api/overview.md
  - base: api/base.md
  - contrast: api/contrast.md
  - ctx: api/ctx.md
  - fov: api/fov.md
  - geometric: api/geometric.md
  - intensity: api/intensity.md
  - io: api/io.md
  - kspace: api/kspace.md
  - labels: api/labels.md
  - noise: api/noise.md
  - psf: api/psf.md
  - qmri: api/qmri.md
  - random: api/random.md
  - special: api/special.md
  - synth: api/synth.md

watch:
- cornucopia
