name: Test on push
description: Test on push

on:
  push:
    paths:
      - cornucopia/**
      - setup.py
      - pyproject.toml
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/test-matrix.yaml
